# ---Defatlt---

# --- Pymarl3 options ---
# runner: "parallel"
env: codertask
# batch_size_run: 8

test_greedy: True
test_nepisode: 32
test_interval: 2000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 2050000
# t_max:10050000
env_args:
  num_users: 5
  n_actions: 6
  map_name: null
  bandwidth: 12


# --- RL hyperparameters ---
gamma: 0.99
buffer_size: 5000
batch_size: 32 # Number of episodes to train on
obs_last_action: False
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm
double_q: True