env: codertask

env_args:
  num_users: 5
  # n_actions: 10
  batch_size: null
  episode_limit: 1
  map_name: null
  bandwidth: 9


test_greedy: True
test_nepisode: 32
test_interval: 2000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 2050000

# obs_agent_id: False
obs_last_action: False
# rnn_hidden_dim: 8